CREATE TABLE `certificates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(255) NOT NULL,
  `overall_length` VARCHAR(255) DEFAULT NULL,
  `blade_length` VARCHAR(255) DEFAULT NULL,
  `handle_length` VARCHAR(255) DEFAULT NULL,
  `blade_material` VARCHAR(255) DEFAULT NULL,
  `blade_thickness` VARCHAR(255) DEFAULT NULL,
  `kissan_length` VARCHAR(255) DEFAULT NULL,
  `hamon` VARCHAR(255) DEFAULT NULL,
  `mekugi` TINYINT DEFAULT NULL,
  `sakihaba` VARCHAR(255) DEFAULT NULL,
  `motohaba` VARCHAR(255) DEFAULT NULL,
  `saya_material` VARCHAR(255) DEFAULT NULL,
  `tsuba_material` VARCHAR(255) DEFAULT NULL,
  `habaki_material` VARCHAR(255) DEFAULT NULL,
  `ito_sageo_material` VARCHAR(255) DEFAULT NULL,
  `forge_id` BIGINT UNSIGNED NOT NULL,
  `swordsmith_id` BIGINT UNSIGNED NOT NULL,
  `date_completed` VARCHAR(255) DEFAULT NULL,
  `no` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_certificates_forge_id` (`forge_id`),
  KEY `idx_certificates_swordsmith_id` (`swordsmith_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
